[workspace]
default-members = ["odilia"]
members = [
  "common",
  "input",
  "odilia",
  "sohkd",
]

[profile.release]
lto = "thin"
codegen-units = 1 # Reduce codegen units for better optimizations (from swhkd)
strip = true # remove debugging symbols from binaries

[workspace.metadata.release]
allow-branch = ["main"]
# By default, crates will not be released or published
# These are overridden on a crate-by-crate basis
release = false
publish = false
shared-version = true
consolidate-commits = true
consolidate-pushes = true
pre-release-commit-message = "Release Odilia version {{version}}"
post-release-commit-message = "Post release version bump: version {{next_version}}"
tag-message = "{{crate_name}} version {{version}}"
dev-version-ext = "dev"
dev-version = true
pre-release-hook = ["cargo", "fmt"]
dependent-version = "upgrade"

[workspace.dependencies]
clap = { version = "^4.0.27", features = ["derive", "wrap_help"] }
eyre = "0.6.8"
nix = "0.25.0"
serde_json = "1.0.89"
sysinfo = "0.26.8"
tokio = { version = "^1.22.0", features = ["sync", "macros", "rt", "signal", "tracing"] }
tracing = "^0.1.37"
zbus = { version = "^3.5.0", default-features = false, features = ["tokio"] }
