[package]
name = "odilia-common"
version = "0.0.1"
authors = ["Michael Connor Buchan <mikey@blindcomputing.org>", "Tait Hoyem <tait@tait.tech>", "Alberto Tirla <albertotirla@gmail.com>"]
description = "Common algorithms and data structures shared by multiple Odilia crates."
license = "gpl-3" # Not gpl-3-or-later
readme = "README.md"
repository = "https://github.com/odilia-app/odilia"
homepage = "https://odilia.app"
keywords = ["screen-reader", "accessibility", "a11y", "tts", "linux"]
categories = ["accessibility"]
edition = "2021"
publish = false

[dependencies]
atspi = { version = "^0.3.6", default-features = false, features = ["tokio"] }
bitflags = "1.3.2"
serde = "1.0.147"
smartstring = "1.0.1"
thiserror = "1.0.37"
tini = "^1.3.0"
zbus.workspace = true
